#!/bin/bash
HERED="$(cd "$(dirname "$0")" && pwd)"
JULES_SOURCE="$1"
IMAGE_ENV='matthewrmshin/ubuntu-gfortran-fcm-make-netcdf'
docker run --rm \
    -u "$(id -u):$(id -g)" \
    -v "${JULES_SOURCE}:/opt/jules" \
    -v "${HERED}/etc/fcm-make/platform/ubuntu.cfg:/opt/jules/etc/fcm-make/platform/ubuntu.cfg" \
    -v "${PWD}:/tmp/jules-build" \
    "${IMAGE_ENV}" \
    env JULES_PLATFORM='ubuntu' \
    fcm make -C '/tmp/jules-build' -f '/opt/jules/etc/fcm-make/make.cfg' \
    'build.target=jules.exe'
